# Generated by Django 4.0.1 on 2022-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='category',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default='2022-01-20 15:31:00.750358'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='owner',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
