# Generated by Django 4.0.1 on 2022-01-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, default='', max_length=100)),
                ('category', models.IntegerField(default='-1')),
                ('availability', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('price_on_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=1000)),
                ('discount', models.FloatField(default='0')),
                ('sale', models.BooleanField(default=False)),
                ('owner', models.TextField(max_length=100)),
                ('unit', models.TextField(blank=True, default='', max_length=10)),
                ('name', models.TextField(max_length=100)),
                ('quantity_stock', models.IntegerField(default='0')),
                ('quantity_sold', models.IntegerField(default='0')),
            ],
            options={
                'ordering': ('comments',),
            },
        ),
    ]
