# Generated by Django 4.0.1 on 2022-01-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_category_alter_sale_name_alter_sale_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default='2022-01-27'),
        ),
    ]
